FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
WORKDIR /app
EXPOSE 5000
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
WORKDIR /src
COPY ["BirdWatcherBackend/BirdWatcherBackend.csproj", "BirdWatcherBackend/"]
#COPY ["BirdWatcherBackend.csproj", "BirdWatcherBackend/"]
RUN dotnet restore "BirdWatcherBackend/BirdWatcherBackend.csproj"
COPY . .
WORKDIR "/src/BirdWatcherBackend"
RUN dotnet build "BirdWatcherBackend.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "BirdWatcherBackend.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "BirdWatcherBackend.dll"]