FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build-env
WORKDIR /app
EXPOSE 5000/tcp

# copy csproj and restore as distinct layer
COPY BirdWatcherBackend.csproj ./
RUN dotnet restore

#Copy everything else and build
COPY . ./
RUN dotnet publish "BirdWatcherBackend.csproj" -c Release -o out

#Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "BirdWatcherBackend.dll"]